openapi: '3.1.2'
info:
  title: Comunicore API
  description: API for analyzing interactions in a forum.
  contact:
    name: API Support
    email: alex19srv@gmail.com
  version: '1.0'
servers:
  - url: https://comunicore.mooo.com/
paths:
  /api/user:
    post:
      operationId: userCreate
      summary: Create a new user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreateResponse'
        "400":
          description: Bad request error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorNotUnique'
                  - $ref: '#/components/schemas/ErrorStringMessage'
        "500":
          $ref: '#/components/responses/ErrorStringDescription'
  /api/user/me:
    get:
      operationId: userMe
      summary: Get current user information
      security:
        - jwtAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreateResponse'
        "401":
          description: client must be authenticated to get his own data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "500":
          $ref: '#/components/responses/ErrorStringDescription'
  /api/user/{userId}:
    parameters:
      - name: userId
        in: path
        description: User id
        required: true
        schema:
          type: integer
    get:
      operationId: userGet
      summary: Get user information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreateResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "401":
          description: client must be authenticated to get user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "403":
          description: client can get only his own data, so if userId in path is not equal to id from token - 403
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "500":
          description: UserNotFound or Internal Server Error
    post:
      operationId: userUpdate
      summary: Update user information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreateResponse'
    delete:
      operationId: userDelete
      summary: Delete a user
      responses:
        '204':
          description: No Content
  /api/auth/login:
    post:
      operationId: authLogin
      summary: User login
      description: |
        Create access and refresh JWT tokens, send to user. The refresh token also stored in a cookie.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthLoginRequest'
      responses:
        '200':
          description: JWT token for authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtToken'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorStringMessage'
        '401':
          description: incorrect login or password or login not exists
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorStringMessage'
        '500':
          $ref: '#/components/responses/ErrorStringDescription'
  /api/auth/refresh:
    post:
      operationId: authRefresh
      summary: Refresh JWT token
      description: |
        Update access and refresh tokens, send to user. The refresh token also stored in a cookie.
      security:
        - cookieAuth: []
      responses:
        '200':
          description: JWT token for authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtToken'
        "401":
          description: Client is not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "500":
          $ref: '#/components/responses/ErrorStringDescription'
  /api/auth/logout:
    post:
      operationId: authLogout
      summary: User logout
      security:
        - cookieAuth: []
      responses:
        '204':
          description: No Content
  /api/threads:
    get:
      operationId: threadsList
      summary: Get list of threads with pagination
      description: |
        Получить список веток с пагинацией. Можно использовать либо постраничную пагинацию (page + limit),
        либо курсорную пагинацию (after или before). Нужно использовать только один параметр.
        after, before или page с номером страницы. Если ни один не указан - выводятся самые свежие сообщения.
        limit - количество сообщений на страницу, по умолчанию 20.
        С разделением на страницы есть неприятная особенность. При удалении или добавлении новых сообщений,
        страницы могут "прыгать". Т.е. у нас есть список (сообщений) и в него могут добавляться и удаляться элементы
        в любом месте списка. Если мы находится на странице 3 и хотим 7-ю, то в ней могут быть совсем другие элементы,
        чем на момент запроса страницы 3. Поэтому для более стабильной пагинации можно использовать курсорную пагинацию.

        Навигация по номеру страницы выберает все сообщения на момент запроса и отдает нужную страницу. Добавление
        или удаление сообщений сбивает это разделение.

        Курсорная пагинация позволяет двигаться вперед и назад по списку, учитывая изменеия в нем.
        Но для нее нужно указывать минимальный или максимальный id сообщения на странице, чтобы понять откуда двигаться
        дальше. И она не позволяет прыгать на конкретную страницу, а только двигаться вперед и назад.
        При этом before и after не включаются в результат, т.е. если указать before=10, то в результат не попадет
        сообщение с id 10, а только с id меньше 10. И аналогично для after. В них указываются id сообщения, но
        before - для получения более старых сообщений, а after - для получения более новых сообщений по времени.
        Более старым сообщениям (before) соответствует меньший id (более старые сообщения),
        а более новым (after) - больший id. И при этом не важно, удалены эти сообщения или нет.
      parameters:
        - name: limit
          in: query
          description: Number of threads to return
          required: false
          schema:
            type: integer
            default: 20
        - name: page
          in: query
          description: Page number (starting from 1)
          required: false
          schema:
            type: integer
            default: 1
        - name: after
          in: query
          description: Return threads created after this id (for cursor pagination)
          required: false
          schema:
            type: integer
        - name: before
          in: query
          description: Return threads created before this id (for cursor pagination)
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadListResponse'
        "401":
          description: client must be authenticated to get threads list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "500":
          $ref: '#/components/responses/ErrorStringDescription'
    post:
      operationId: threadCreate
      summary: Create a new thread
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThreadCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadListItem'
        "401":
          $ref: '#/components/responses/ErrorStringDescription'
        "500":
          $ref: '#/components/responses/ErrorStringDescription'
  /api/threads/{threadId}:
    get:
      operationId: threadGet
      summary: Get single thread with all posts by thread id
      parameters:
        - name: threadId
          in: path
          description: Thread id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadWithPostsListResponse'
        "400":
          $ref: '#/components/responses/ErrorStringDescription'
        "500":
          $ref: '#/components/responses/ErrorStringDescription'
  /api/threads/{threadId}/posts:
    post:
      operationId: threadAddPost
      summary: Add a new post to thread
      parameters:
        - name: threadId
          in: path
          description: Thread id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThreadCreatePostRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadPostItem'
        "400":
          $ref: '#/components/responses/ErrorStringDescription'
        "500":
          $ref: '#/components/responses/ErrorStringDescription'
  /api/media:
    post:
      summary: Upload media file
      operationId: mediaUpload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MediaUploadRequest'
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/MediaUploadRequest'
      responses:
        '200':
          description: Uploaded file URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaUploadResponse'
        "401":
          description: Client is not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
  /storage/media/{fileName}:
    get:
      summary: Get media file by name
      operationId: mediaGet
      security: []
      parameters:
        - name: fileName
          in: path
          description: File name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "401":
          description: Client is not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "404":
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStringMessage'
        "500":
          $ref: '#/components/responses/ErrorStringDescription'
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth: # for JWT refresh token
      type: apiKey
      in: cookie
      name: refreshToken
  responses:
    ErrorStringDescription:
      description: Error in request with string description (for log, not for user).
      content:
        application/json:
          schema:
            type: string
  schemas:
    JwtToken:
      type: object
      properties:
        refreshToken:
          type: string
        accessToken:
          type: string
      required:
        - refreshToken
        - accessToken
      example:
        refreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlzcyI6ImZvcnVtIiwiZXhwIjoxNzcyNjU5MDgxLCJqdGkiOiJBWnk2bTRoamUvSytkRkVmS25QTEtnIn0.UmYW5WZIZ4CaqmsycXXzhjmOqY2G-IM3DncogTA7uno"
        accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlzcyI6ImZvcnVtIiwiZXhwIjoxNzcyNjU5MDgxLCJqdGkiOiJBWnk2bTRoamUvSytkRkVmS25QTEtnIn0.UmYW5WZIZ4CaqmsycXXzhjmOqY2G-IM3DncogTA7uno"
    UserCreateRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 8
      required:
        - name
        - email
        - password
      example:
        name: "john_doe"
        email: "john.doe@example.com"
        password: "securepassword123"
    UserGetResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - name
        - email
      example:
        id: 1
        name: "john_doe"
        email: "test@mail.ru"
    UserCreateResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - name
        - email
      example:
        id: 1
        name: "john_doe"
        email: "test@mail.ru"
    UserUpdateRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - name
        - email
        - password
      example:
        name: "john_doe"
        email: "john.doe@example.com"
        password: "securepassword123"
    AuthLoginRequest:
      type: object
      properties:
        login:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - login
        - password
      example:
        login: "john.doe@example.com"
        password: "securepassword123"
    ThreadListResponse:
      type: object
      properties:
        threads:
          type: array
          items:
            $ref: '#/components/schemas/ThreadListItem'
        total_count_estimated:
          type: integer
        have_prev:
          type: boolean
        have_next:
          type: boolean
      required:
        - threads
        - total_count_estimated
        - have_prev
        - have_next
      example:
        threads:
          - id: 1
            title: "First thread"
            content: "This is the content of the first thread."
            author_id: 42
            author_name: "Petr Semenov"
            posts_count: 5
            created_at: "2024-01-01T12:00:00Z"
          - id: 2
            title: "Second thread"
            content: "This is the content of the second thread."
            author_id: 43
            author_name: "Anna Ivanova"
            posts_count: 3
            created_at: "2024-01-02T15:30:00Z"
        total_count_estimated: 100
        have_prev: false
        have_next: true
    ThreadListItem:
      type: object
      properties:
        id:
          type: integer
        author_id:
          type: integer
        author_name:
          type: string
        title:
          type: string
        content:
          type: string
        posts_count:
          type: integer
        created_at:
          type: string
          format: date-time
      required:
        - id
        - author_id
        - author_name
        - title
        - content
        - posts_count
        - created_at
      example:
        id: 1
        title: "First thread"
        content: "This is the content of the first thread."
        author_id: 42
        author_name: "Petr Semenov"
        posts_count: 5
        created_at: "2024-01-01T12:00:00Z"
    ThreadWithPostsListResponse:
      type: object
      properties:
        id:
          type: integer
        author_id:
          type: integer
        author_name:
          type: string
        title:
          type: string
        content:
          type: string
        posts_count:
          type: integer
        created_at:
          type: string
          format: date-time
        posts:
          type: array
          items:
            $ref: '#/components/schemas/ThreadPostItem'
      required:
        - id
        - author_id
        - author_name
        - title
        - content
        - posts_count
        - created_at
        - posts
      example:
        id: 1
        title: "First thread"
        content: "This is the content of the first thread."
        author_id: 42
        author_name: "Petr Semenov"
        posts_count: 5
        created_at: "2024-01-01T12:00:00Z"
        posts:
          - id: 1
            content: "This is the content of the first post."
            author_id: 42
            author_name: "Petr Semenov"
            created_at: "2024-01-01T12:00:00Z"
          - id: 2
            content: "This is the content of the second post."
            author_id: 43
            author_name: "Anna Ivanova"
            created_at: "2024-01-02T15:30:00Z"
    ThreadPostItem:
      type: object
      properties:
        id:
          type: integer
        author_id:
          type: integer
        author_name:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - author_id
        - author_name
        - content
        - created_at
      example:
        id: 1
        content: "Первый ответ в ветке."
        author_id: 42
        author_name: "Petr Semenov"
        posts_count: 5
        created_at: "2024-01-01T12:00:00Z"
    ThreadCreateRequest:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content
      example:
        title: "How to learn Go?"
        content: "I want to learn Go, but I don't know where to start. Any advice?"
    ThreadCreatePostRequest:
      type: object
      properties:
        content:
          type: string
      required:
        - content
      example:
        content: "I want to learn Go, but I don't know where to start. Any advice?"
    # media (files)
    MediaUploadRequest:
      type: object
      properties:
        content:
          type: string
          format: binary
      required: [ content ]
      example:
        content: (binary file content)
    MediaUploadResponse:
      type: object
      properties:
        fileName:
          type: string
        url:
          type: string
          format: uri
      required: [url, fileName]
    # errors
    ErrorStringMessage:
      description: |
        Error with just string message, without code or other data. For simple errors,
        when we don't need to send any additional data, just a message for log.
      type: object
      properties:
        code:
          type: string
          enum: ["ErrorStringMessage"]
          example: "ErrorStringMessage"
        message:
          type: string
      example:
        message: "Some error description for log"
      required:
        - message
    ErrorNotUnique:
      description: Error in some of listed parameters, one or more is not unique.
      type: object
      properties:
        code:
          type: string
          enum: ["ErrorNotUnique"]
          example: "ErrorNotUnique"
        data:
          type: array
          items:
            type: string
          example:
            - "email"
            - "name"
      required:
        - code
        - params
security:
  - jwtAuth: []
